/* ═══════════════════════════════════════════════════════
   products.js — Catalogue Alkamar Info
   Taux de conversion : 1 EUR = 491 KMF
═══════════════════════════════════════════════════════ */

const PRODUCTS = [

  /* ── PC PORTABLES ────────────────────────────────── */
  {
    id: 'lenovo-ideapad-3',
    brand: 'Lenovo', subcategory: 'portables',
    name: 'IdeaPad 3 15"', subtitle: 'Intel Celeron N4020 · 4 Go · 128 Go SSD · 15.6" HD',
    price: 249, priceKmf: 122200, priceOld: null,
    badge: 'Bon prix', badgeClass: 'badge--deal',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 64,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Lenovo+IdeaPad+3',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=Vue+principale','https://placehold.co/500x380/f1f5f9/64748b?text=Clavier','https://placehold.co/500x380/f1f5f9/64748b?text=Ports'],
    features: ['Processeur efficace pour bureautique', 'SSD rapide au démarrage', 'Windows 11 S inclus', 'Autonomie 7h'],
    specs: {
      'Processeur': 'Intel Celeron N4020 (2 cœurs, 2.8 GHz)',
      'Mémoire RAM': '4 Go DDR4 2400 MHz',
      'Stockage': '128 Go SSD M.2',
      'Écran': '15.6" HD (1366×768), anti-reflets',
      'Système': 'Windows 11 S (mise à jour W11 gratuite)',
      'Connectique': '1× USB-C, 2× USB 3.0, HDMI, jack 3.5mm',
      'Réseau': 'WiFi 5 (802.11ac), Bluetooth 4.1',
      'Webcam': 'HD 720p intégrée',
      'Batterie': 'Li-ion 38 Wh — autonomie ~7h',
      'Dimensions': '359 × 235 × 19.9 mm',
      'Poids': '1.70 kg',
      'Garantie': '24 mois constructeur',
    },
    description: "Le Lenovo IdeaPad 3 est la solution bureautique accessible par excellence. Son processeur Celeron N4020 associé à 4 Go de RAM couvre parfaitement la navigation web, la suite Office, les emails et le streaming vidéo. Son SSD garantit un démarrage rapide et une réactivité quotidienne agréable. Idéal pour les étudiants, les débutants ou comme second ordinateur.",
  },
  {
    id: 'hp-15s-fq5',
    brand: 'HP', subcategory: 'portables',
    name: 'HP 15s-fq5010nf', subtitle: 'Intel Core i3-1215U · 8 Go · 256 Go SSD · 15.6" FHD',
    price: 349, priceKmf: 171400, priceOld: null,
    badge: 'Nouveau', badgeClass: 'badge--new',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 112,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=HP+15s',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=HP+15s+face','https://placehold.co/500x380/f1f5f9/64748b?text=HP+15s+clavier','https://placehold.co/500x380/f1f5f9/64748b?text=HP+15s+ports'],
    features: ['Core i3 12e génération', '8 Go RAM — multitâche fluide', 'SSD 256 Go', 'Écran Full HD'],
    specs: {
      'Processeur': 'Intel Core i3-1215U (6 cœurs, jusqu\'à 4.4 GHz)',
      'Mémoire RAM': '8 Go DDR4 3200 MHz',
      'Stockage': '256 Go SSD PCIe NVMe',
      'Écran': '15.6" Full HD (1920×1080), dalle TN',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C, 2× USB 3.0, 1× USB 2.0, HDMI, jack',
      'Réseau': 'WiFi 5, Bluetooth 5.0',
      'Webcam': 'HD 720p',
      'Batterie': '41 Wh — autonomie ~10h',
      'Poids': '1.69 kg',
      'Garantie': '24 mois constructeur',
    },
    description: "Le HP 15s avec son Core i3-1215U de 12e génération offre un bond de performance significatif par rapport aux modèles d'entrée de gamme. Les 8 Go de RAM permettent un vrai multitâche : plusieurs onglets, musique en fond, appels visio — tout fonctionne sans accroc. Un rapport qualité/prix excellent pour le travail et les études.",
  },
  {
    id: 'acer-aspire-5-a515',
    brand: 'Acer', subcategory: 'portables',
    name: 'Aspire 5 A515-57', subtitle: 'Intel Core i5-1235U · 8 Go · 512 Go SSD · 15.6" FHD IPS',
    price: 449, priceKmf: 220500, priceOld: null,
    badge: 'Populaire', badgeClass: 'badge--deal',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 198,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Acer+Aspire+5',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=Aspire+5+face','https://placehold.co/500x380/f1f5f9/64748b?text=Aspire+5+dos','https://placehold.co/500x380/f1f5f9/64748b?text=Aspire+5+ports'],
    features: ['Core i5 12e génération', 'Dalle IPS — couleurs précises', '512 Go NVMe', 'Lecteur d\'empreinte'],
    specs: {
      'Processeur': 'Intel Core i5-1235U (10 cœurs, jusqu\'à 4.4 GHz)',
      'Mémoire RAM': '8 Go DDR4 3200 MHz (extensible 32 Go)',
      'Stockage': '512 Go SSD PCIe NVMe',
      'Écran': '15.6" Full HD IPS (1920×1080), 45% NTSC',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C (Thunderbolt 4), 2× USB 3.2, 1× USB 2.0, HDMI 2.0, jack',
      'Réseau': 'WiFi 6 (802.11ax), Bluetooth 5.1',
      'Webcam': 'HD 720p + micro intégré',
      'Batterie': '57.5 Wh — autonomie ~10h',
      'Poids': '1.73 kg',
      'Garantie': '24 mois constructeur',
    },
    description: "L'Acer Aspire 5 A515-57 est la référence polyvalente du milieu de gamme. Son Core i5-1235U hybride (2 P-cores + 8 E-cores) gère aussi bien le travail intensif que les tâches légères. La dalle IPS 15.6\" offre une meilleure reproduction des couleurs et des angles de vision larges. Avec 512 Go de SSD et un port USB-C Thunderbolt 4, il est taillé pour durer.",
  },
  {
    id: 'lenovo-ideapad-5-14',
    brand: 'Lenovo', subcategory: 'portables',
    name: 'IdeaPad 5 14"', subtitle: 'AMD Ryzen 5 5500U · 8 Go · 512 Go SSD · 14" FHD IPS',
    price: 499, priceKmf: 245000, priceOld: null,
    badge: null, badgeClass: '',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 156,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Lenovo+IdeaPad+5',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=IdeaPad+5+face','https://placehold.co/500x380/f1f5f9/64748b?text=IdeaPad+5+clavier','https://placehold.co/500x380/f1f5f9/64748b?text=IdeaPad+5+ports'],
    features: ['Ryzen 5 — excellente performance', 'Léger 1.46 kg', 'Dalle IPS 14"', 'Autonomie 10h'],
    specs: {
      'Processeur': 'AMD Ryzen 5 5500U (6 cœurs 12 threads, jusqu\'à 4.0 GHz)',
      'Mémoire RAM': '8 Go DDR4 3200 MHz (extensible 16 Go)',
      'Stockage': '512 Go SSD PCIe NVMe',
      'Écran': '14" Full HD IPS (1920×1080), anti-reflets',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C 3.2, 2× USB 3.0, 1× USB 2.0, HDMI, jack',
      'Réseau': 'WiFi 6, Bluetooth 5.1',
      'Webcam': 'HD 720p + cache physique',
      'Batterie': '56 Wh — autonomie ~10h',
      'Poids': '1.46 kg',
      'Garantie': '24 mois constructeur',
    },
    description: "Le Lenovo IdeaPad 5 14\" est l'ultraportable qui ne sacrifie rien. Son Ryzen 5 5500U offre une puissance de traitement exceptionnelle, idéale pour la créativité, la programmation légère et le travail en déplacement. À seulement 1.46 kg, il est l'un des plus légers de sa catégorie tout en embarquant une batterie généreuse pour 10h d'autonomie.",
  },
  {
    id: 'asus-vivobook-15',
    brand: 'Asus', subcategory: 'portables',
    name: 'VivoBook 15 X1502', subtitle: 'Intel Core i5-1235U · 16 Go · 512 Go SSD · 15.6" FHD',
    price: 549, priceKmf: 269500, priceOld: null,
    badge: 'Nouveau', badgeClass: 'badge--new',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 89,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Asus+VivoBook+15',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=VivoBook+face','https://placehold.co/500x380/f1f5f9/64748b?text=VivoBook+clavier','https://placehold.co/500x380/f1f5f9/64748b?text=VivoBook+ports'],
    features: ['16 Go RAM — vrai multitâche', 'Core i5 + GPU Iris Xe', 'Clavier rétroéclairé', 'Design slim'],
    specs: {
      'Processeur': 'Intel Core i5-1235U (10 cœurs, jusqu\'à 4.4 GHz)',
      'Mémoire RAM': '16 Go DDR4 3200 MHz',
      'Stockage': '512 Go SSD PCIe NVMe',
      'Écran': '15.6" Full HD (1920×1080), 60Hz, anti-reflets',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C, 2× USB 3.2, 1× USB 2.0, HDMI 1.4, jack, lecteur SD',
      'Réseau': 'WiFi 6 (802.11ax), Bluetooth 5.0',
      'Webcam': 'HD 720p avec obturateur physique',
      'Batterie': '50 Wh — autonomie ~8h',
      'Poids': '1.75 kg',
      'Garantie': '24 mois constructeur',
    },
    description: "Avec 16 Go de RAM, l'Asus VivoBook 15 X1502 est le PC portable polyvalent pour les utilisateurs exigeants. Montage vidéo léger, développement web, design graphique, jeux indie — tout passe sans ralentissement. Son clavier rétroéclairé est apprécié pour travailler dans toutes les conditions.",
  },
  {
    id: 'dell-inspiron-15-3520',
    brand: 'Dell', subcategory: 'portables',
    name: 'Inspiron 15 3520', subtitle: 'Intel Core i5-1235U · 8 Go · 512 Go SSD · 15.6" FHD',
    price: 499, priceKmf: 245000, priceOld: null,
    badge: null, badgeClass: '',
    stock: 'Stock limité', stockClass: 'low-stock',
    rating: 4, ratingCount: 143,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Dell+Inspiron+15',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=Inspiron+face','https://placehold.co/500x380/f1f5f9/64748b?text=Inspiron+cote','https://placehold.co/500x380/f1f5f9/64748b?text=Inspiron+ports'],
    features: ['Fiabilité Dell reconnue', 'Core i5 12e gen', 'Lecteur carte SD', 'Design compact'],
    specs: {
      'Processeur': 'Intel Core i5-1235U (10 cœurs, jusqu\'à 4.4 GHz)',
      'Mémoire RAM': '8 Go DDR4 (extensible 32 Go)',
      'Stockage': '512 Go SSD PCIe NVMe',
      'Écran': '15.6" Full HD (1920×1080), anti-reflets',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C 3.2, 2× USB 3.2, 1× USB 2.0, HDMI, jack, lecteur SD',
      'Réseau': 'WiFi 5, Bluetooth 5.0',
      'Webcam': 'HD 720p',
      'Batterie': '41 Wh — autonomie ~7h',
      'Poids': '1.69 kg',
      'Garantie': '24 mois constructeur',
    },
    description: "Le Dell Inspiron 15 3520 incarne la fiabilité et la solidité de la marque Dell à un prix accessible. Son Core i5-1235U assure une fluidité au quotidien pour tous les usages professionnels et personnels. Le lecteur de carte SD intégré est très pratique pour les photographes et vidéastes occasionnels.",
  },

  /* ── PC DE BUREAU ────────────────────────────────── */
  {
    id: 'lenovo-thinkcentre-m75q',
    brand: 'Lenovo', subcategory: 'bureau',
    name: 'ThinkCentre M75q Gen 2', subtitle: 'Ryzen 3 PRO 4350GE · 8 Go · 256 Go SSD · Tiny',
    price: 389, priceKmf: 191000, priceOld: null,
    badge: 'Bon prix', badgeClass: 'badge--deal',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 74,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=ThinkCentre+M75q',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=M75q+face','https://placehold.co/500x380/f1f5f9/64748b?text=M75q+dos','https://placehold.co/500x380/f1f5f9/64748b?text=M75q+ports'],
    features: ['Format Tiny ultra compact', 'Ryzen PRO fiable', 'Windows 11 Pro inclus', 'VESA montable'],
    specs: {
      'Processeur': 'AMD Ryzen 3 PRO 4350GE (4 cœurs, jusqu\'à 3.9 GHz)',
      'Mémoire RAM': '8 Go DDR4 3200 MHz (extensible 64 Go)',
      'Stockage': '256 Go SSD M.2 PCIe NVMe',
      'Système': 'Windows 11 Pro',
      'Connectique': '1× USB-C, 4× USB 3.2, 2× USB 2.0, HDMI, DisplayPort, RJ45',
      'Réseau': 'Ethernet Gigabit, WiFi 6, Bluetooth 5.0',
      'Format': 'Tiny (179 × 183 × 37 mm)',
      'Poids': '1.35 kg',
      'Garantie': '36 mois constructeur',
    },
    description: "Le ThinkCentre M75q Gen 2 est le PC de bureau professionnel qui tient dans la poche. Son format Tiny permet de le fixer derrière un écran (kit VESA en option) et de libérer le bureau. Avec Windows 11 Pro et le processeur Ryzen 3 PRO, il est taillé pour les environnements d'entreprise, les caisses enregistreuses, et les bureaux partagés.",
  },
  {
    id: 'hp-prodesk-400-g7',
    brand: 'HP', subcategory: 'bureau',
    name: 'ProDesk 400 G7 MT', subtitle: 'Intel Core i5-10500 · 8 Go · 256 Go SSD · Tour Micro',
    price: 449, priceKmf: 220500, priceOld: null,
    badge: null, badgeClass: '',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 52,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=HP+ProDesk+400',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=ProDesk+face','https://placehold.co/500x380/f1f5f9/64748b?text=ProDesk+interieur'],
    features: ['i5-10500 solide', 'Extensible facilement', 'Windows 11 Pro', 'Lecteur DVD intégré'],
    specs: {
      'Processeur': 'Intel Core i5-10500 (6 cœurs 12 threads, jusqu\'à 4.5 GHz)',
      'Mémoire RAM': '8 Go DDR4 2666 MHz (extensible 128 Go)',
      'Stockage': '256 Go SSD M.2 NVMe',
      'Système': 'Windows 11 Pro',
      'Connectique': '6× USB 3.2, 2× USB 2.0, VGA, DisplayPort, PS/2, jack',
      'Réseau': 'Ethernet Gigabit Intel, WiFi optionnel',
      'Optique': 'Lecteur DVD-RW intégré',
      'Format': 'Tour Micro (16.6L)',
      'Garantie': '36 mois constructeur',
    },
    description: "Le HP ProDesk 400 G7 est le PC de bureau professionnel par excellence. Robuste, extensible et facile à maintenir, il convient aux PME, administrations et bureaux. Le Core i5-10500 avec 6 cœurs gère sans problème les logiciels de comptabilité, de gestion, et le multitâche intensif.",
  },
  {
    id: 'dell-optiplex-3090',
    brand: 'Dell', subcategory: 'bureau',
    name: 'OptiPlex 3090 MT', subtitle: 'Intel Core i5-10505 · 16 Go · 512 Go SSD · Tour',
    price: 549, priceKmf: 269500, priceOld: null,
    badge: 'Nouveau', badgeClass: 'badge--new',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 38,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Dell+OptiPlex',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=OptiPlex+face'],
    features: ['16 Go RAM', '512 Go SSD', 'USB-C en façade', 'Gestion à distance'],
    specs: {
      'Processeur': 'Intel Core i5-10505 (6 cœurs 12 threads, jusqu\'à 4.6 GHz)',
      'Mémoire RAM': '16 Go DDR4 2666 MHz',
      'Stockage': '512 Go SSD PCIe NVMe',
      'Système': 'Windows 11 Pro',
      'Connectique': '1× USB-C, 5× USB 3.2, 2× USB 2.0, HDMI, 2× DisplayPort, RJ45',
      'Réseau': 'Ethernet Gigabit, WiFi 6 optionnel',
      'Sécurité': 'TPM 2.0, châssis verrouillable',
      'Garantie': '36 mois on-site constructeur',
    },
    description: "Le Dell OptiPlex 3090 combine puissance, fiabilité et gérabilité pour les entreprises. Avec 16 Go de RAM et 512 Go de SSD, il traite sans effort les charges de travail bureautiques les plus lourdes. Son USB-C en façade et ses deux ports DisplayPort permettent de connecter deux écrans simultanément.",
  },
  {
    id: 'asus-expertcenter-d500tc',
    brand: 'Asus', subcategory: 'bureau',
    name: 'ExpertCenter D500TC', subtitle: 'Intel Core i7-10700 · 16 Go · 512 Go SSD · Tour',
    price: 649, priceKmf: 318600, priceOld: null,
    badge: null, badgeClass: '',
    stock: 'Stock limité', stockClass: 'low-stock',
    rating: 4, ratingCount: 29,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Asus+ExpertCenter',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=ExpertCenter+face'],
    features: ['Core i7 8 cœurs', '16 Go RAM', 'Extensible PCIe x16', 'Windows 11 Pro'],
    specs: {
      'Processeur': 'Intel Core i7-10700 (8 cœurs 16 threads, jusqu\'à 4.8 GHz)',
      'Mémoire RAM': '16 Go DDR4 2933 MHz (extensible 128 Go)',
      'Stockage': '512 Go SSD PCIe NVMe',
      'Système': 'Windows 11 Pro',
      'Connectique': '1× USB-C, 4× USB 3.2, 2× USB 2.0, 2× DP, HDMI, RJ45',
      'Extension': 'Slot PCIe x16 libre (GPU ajoutaable)',
      'Réseau': 'Ethernet Gigabit, WiFi 6',
      'Garantie': '36 mois constructeur',
    },
    description: "L'Asus ExpertCenter D500TC avec son Core i7-10700 à 8 cœurs est un vrai PC de puissance pour les professionnels. Il peut accueillir une carte graphique dédiée via son slot PCIe x16, ce qui le rend évolutif sur le long terme. Parfait pour l'architecture, la comptabilité complexe, ou le développement logiciel.",
  },
  {
    id: 'acer-veriton-m4680g',
    brand: 'Acer', subcategory: 'bureau',
    name: 'Veriton M4680G', subtitle: 'Intel Core i5-11400 · 8 Go · 256 Go SSD + 1 To HDD',
    price: 479, priceKmf: 235200, priceOld: null,
    badge: 'Bon prix', badgeClass: 'badge--deal',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 41,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Acer+Veriton+M4680G',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=Veriton+face'],
    features: ['SSD + HDD 1 To combo', 'i5-11400 6 cœurs', 'Dual display', 'Windows 11 Pro'],
    specs: {
      'Processeur': 'Intel Core i5-11400 (6 cœurs 12 threads, jusqu\'à 4.4 GHz)',
      'Mémoire RAM': '8 Go DDR4 3200 MHz',
      'Stockage': '256 Go SSD NVMe + 1 To HDD',
      'Système': 'Windows 11 Pro',
      'Connectique': '1× USB-C, 4× USB 3.2, 4× USB 2.0, 2× DisplayPort, HDMI, RJ45',
      'Réseau': 'Ethernet Gigabit, WiFi 6',
      'Garantie': '36 mois constructeur',
    },
    description: "L'Acer Veriton M4680G est la combinaison parfaite pour les professionnels qui ont besoin à la fois de rapidité (SSD 256 Go) et de grande capacité de stockage (HDD 1 To). Son Core i5-11400 de 11e génération assure des performances excellentes pour toutes les applications métier.",
  },

  /* ── PC GAMING ───────────────────────────────────── */
  {
    id: 'lenovo-ideapad-gaming-3',
    brand: 'Lenovo', subcategory: 'gaming',
    name: 'IdeaPad Gaming 3', subtitle: 'Ryzen 5 5600H · RTX 3050 · 8 Go · 512 Go · 15.6" 120Hz',
    price: 699, priceKmf: 343200, priceOld: null,
    badge: 'Bon prix', badgeClass: 'badge--deal',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 187,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=IdeaPad+Gaming+3',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=Gaming+3+face','https://placehold.co/500x380/f1f5f9/64748b?text=Gaming+3+dos'],
    features: ['RTX 3050 — jeux en 1080p', 'Écran 120Hz fluide', 'Ryzen 5 5600H', 'Clavier rétroéclairé RGB'],
    specs: {
      'Processeur': 'AMD Ryzen 5 5600H (6 cœurs 12 threads, jusqu\'à 4.2 GHz)',
      'GPU': 'Nvidia GeForce RTX 3050 4 Go GDDR6',
      'Mémoire RAM': '8 Go DDR4 3200 MHz (extensible 32 Go)',
      'Stockage': '512 Go SSD PCIe NVMe',
      'Écran': '15.6" Full HD IPS 120Hz, anti-reflets',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C, 2× USB 3.2, 1× USB 2.0, HDMI 2.0, RJ45, jack',
      'Clavier': 'Rétroéclairé blanc, 1 zone',
      'Batterie': '60 Wh — ~5h (gaming) / ~8h (bureautique)',
      'Poids': '2.20 kg',
      'Garantie': '24 mois constructeur',
    },
    description: "Le Lenovo IdeaPad Gaming 3 est la porte d'entrée idéale dans le gaming PC portable. Son duo Ryzen 5 5600H + RTX 3050 tourne facilement Fortnite, GTA V, Valorant, FIFA en Full HD avec les détails réglés sur Moyen/Élevé. L'écran 120Hz rend l'expérience visiblement plus fluide comparé aux 60Hz classiques.",
  },
  {
    id: 'acer-nitro-5-an515',
    brand: 'Acer', subcategory: 'gaming',
    name: 'Nitro 5 AN515-58', subtitle: 'Intel Core i5-12500H · RTX 3050 · 8 Go · 512 Go · 144Hz',
    price: 749, priceKmf: 367800, priceOld: null,
    badge: 'Nouveau', badgeClass: 'badge--new',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 234,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Acer+Nitro+5',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=Nitro+5+face','https://placehold.co/500x380/f1f5f9/64748b?text=Nitro+5+RGB'],
    features: ['Core i5 12e gen hybride', '144Hz — gaming fluide', 'Double ventilateur DualFan', 'USB-C PD'],
    specs: {
      'Processeur': 'Intel Core i5-12500H (12 cœurs, jusqu\'à 4.5 GHz)',
      'GPU': 'Nvidia GeForce RTX 3050 4 Go GDDR6',
      'Mémoire RAM': '8 Go DDR5 4800 MHz (extensible 32 Go)',
      'Stockage': '512 Go SSD PCIe Gen4 NVMe',
      'Écran': '15.6" Full HD IPS 144Hz, 100% sRGB',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C (PD 140W), 1× USB-C, 2× USB 3.2, 1× USB 2.0, HDMI 2.1, RJ45, jack',
      'Clavier': 'Rétroéclairé RGB par zones',
      'Poids': '2.50 kg',
      'Garantie': '24 mois constructeur',
    },
    description: "L'Acer Nitro 5 combine un processeur Intel Core i5-12500H de 12e génération (architecture hybride) avec la RTX 3050 pour une expérience gaming solide. L'écran 144Hz est l'un des points forts : les animations et les jeux rapides sont nettement plus agréables qu'en 60Hz. La RAM DDR5 4800 MHz lui donne une longueur d'avance sur les modèles concurrents.",
  },
  {
    id: 'asus-tuf-gaming-a15',
    brand: 'Asus', subcategory: 'gaming',
    name: 'TUF Gaming A15', subtitle: 'Ryzen 7 7745HX · RTX 4060 · 16 Go · 512 Go · 144Hz',
    price: 899, priceKmf: 441400, priceOld: null,
    badge: 'Top vente', badgeClass: 'badge--promo',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 312,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=TUF+Gaming+A15',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=TUF+face','https://placehold.co/500x380/f1f5f9/64748b?text=TUF+RGB','https://placehold.co/500x380/f1f5f9/64748b?text=TUF+ports'],
    features: ['RTX 4060 — ultra-performances', 'MUX Switch dédié', '16 Go RAM DDR5', 'Certification MIL-STD'],
    specs: {
      'Processeur': 'AMD Ryzen 7 7745HX (8 cœurs 16 threads, jusqu\'à 5.1 GHz)',
      'GPU': 'Nvidia GeForce RTX 4060 8 Go GDDR6',
      'Mémoire RAM': '16 Go DDR5 4800 MHz (extensible 32 Go)',
      'Stockage': '512 Go SSD PCIe Gen4 NVMe (2e slot libre)',
      'Écran': '15.6" Full HD IPS 144Hz, 100% sRGB, 3ms',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C (DP+PD), 3× USB 3.2, HDMI 2.1 (8K), RJ45, jack',
      'Clavier': 'RGB rétroéclairé 4 zones, anti-ghosting',
      'MUX Switch': 'Oui — GPU dédié direct pour +15% perfs',
      'Poids': '2.20 kg',
      'Certification': 'MIL-STD-810H',
      'Garantie': '24 mois constructeur',
    },
    description: "L'Asus TUF Gaming A15 est la référence gaming milieu de gamme 2024. Son Ryzen 7 7745HX couplé à la RTX 4060 permet de jouer en 1080p Ultra/High dans pratiquement tous les jeux actuels — Cyberpunk 2077, Call of Duty, Hogwarts Legacy. Le MUX Switch améliore les performances de ~15% en court-circuitant l'iGPU. Certifié militaire MIL-STD-810H, il résiste aux chocs et variations de température.",
  },
  {
    id: 'msi-thin-gf63',
    brand: 'MSI', subcategory: 'gaming',
    name: 'Thin GF63 12UC', subtitle: 'Intel Core i5-12450H · RTX 3050 · 8 Go · 512 Go · 144Hz',
    price: 729, priceKmf: 357900, priceOld: null,
    badge: null, badgeClass: '',
    stock: 'Stock limité', stockClass: 'low-stock',
    rating: 4, ratingCount: 98,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=MSI+Thin+GF63',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=GF63+face'],
    features: ['Design fin 19.8mm', 'i5-12450H 8 cœurs', 'RTX 3050 Ti', 'Léger 1.86 kg'],
    specs: {
      'Processeur': 'Intel Core i5-12450H (8 cœurs, jusqu\'à 4.4 GHz)',
      'GPU': 'Nvidia GeForce RTX 3050 4 Go GDDR6',
      'Mémoire RAM': '8 Go DDR4 3200 MHz',
      'Stockage': '512 Go SSD NVMe',
      'Écran': '15.6" Full HD IPS 144Hz',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C, 2× USB 3.2, 1× USB 2.0, HDMI, RJ45, jack',
      'Épaisseur': '19.8 mm',
      'Poids': '1.86 kg',
      'Garantie': '24 mois constructeur',
    },
    description: "Le MSI Thin GF63 est le PC gaming le plus fin et léger de sa catégorie. À seulement 19.8mm d'épaisseur et 1.86 kg, il s'emporte partout sans effort. Son Core i5-12450H et la RTX 3050 assurent de bonnes performances gaming, idéal pour ceux qui veulent un PC gaming nomade sans compromis sur la portabilité.",
  },
  {
    id: 'hp-victus-15',
    brand: 'HP', subcategory: 'gaming',
    name: 'Victus 15', subtitle: 'Intel Core i5-12500H · RTX 3050 · 8 Go · 512 Go · 144Hz',
    price: 699, priceKmf: 343200, priceOld: 799,
    badge: 'Promo', badgeClass: 'badge--promo',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 167,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=HP+Victus+15',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=Victus+face','https://placehold.co/500x380/f1f5f9/64748b?text=Victus+clavier'],
    features: ['Prix réduit -100€', 'i5-12500H 12 cœurs', 'Design sobre', 'Refroidissement Omen'],
    specs: {
      'Processeur': 'Intel Core i5-12500H (12 cœurs, jusqu\'à 4.5 GHz)',
      'GPU': 'Nvidia GeForce RTX 3050 4 Go GDDR6',
      'Mémoire RAM': '8 Go DDR4 3200 MHz',
      'Stockage': '512 Go SSD PCIe NVMe',
      'Écran': '15.6" Full HD IPS 144Hz',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C, 2× USB 3.2, 1× USB 2.0, HDMI 2.1, RJ45, jack',
      'Refroidissement': 'Double ventilateur HP Omen Tempest',
      'Poids': '2.37 kg',
      'Garantie': '24 mois constructeur',
    },
    description: "Le HP Victus 15 est en promotion à 699€ au lieu de 799€ — une opportunité à ne pas rater. Son Core i5-12500H hybride (4 P-cores + 8 E-cores) est l'un des plus performants de sa génération. Associé à la RTX 3050, il gère parfaitement les jeux populaires en Full HD. Le système de refroidissement double ventilateur HP Omen assure des températures stables en session gaming prolongée.",
  },

  /* ── TOUT-EN-UN ──────────────────────────────────── */
  {
    id: 'hp-aio-24',
    brand: 'HP', subcategory: 'toutunun',
    name: 'All-in-One 24-cb1025nf', subtitle: 'Intel Core i5-1235U · 8 Go · 512 Go · 23.8" FHD',
    price: 699, priceKmf: 343200, priceOld: null,
    badge: 'Nouveau', badgeClass: 'badge--new',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 67,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=HP+AIO+24',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=HP+AIO+face','https://placehold.co/500x380/f1f5f9/64748b?text=HP+AIO+arriere'],
    features: ['Zéro câble sur le bureau', 'Webcam FHD 5Mp', 'WiFi 6', 'Haut-parleurs intégrés'],
    specs: {
      'Processeur': 'Intel Core i5-1235U (10 cœurs, jusqu\'à 4.4 GHz)',
      'Mémoire RAM': '8 Go DDR4 3200 MHz',
      'Stockage': '512 Go SSD PCIe NVMe',
      'Écran': '23.8" Full HD IPS (1920×1080), anti-reflets',
      'Système': 'Windows 11 Home',
      'Webcam': '5 Mp Full HD avec obturateur physique',
      'Audio': 'Haut-parleurs stéréo 5W intégrés',
      'Connectique': '2× USB-C, 4× USB 3.2, HDMI, lecteur SD, jack',
      'Réseau': 'WiFi 6 (802.11ax), Bluetooth 5.0, RJ45',
      'Garantie': '24 mois constructeur',
    },
    description: "Le HP All-in-One 24 est la solution bureau ultime pour ceux qui veulent un poste de travail propre et sans encombrement. Tout est intégré dans l'écran de 23.8\" : processeur, RAM, SSD, webcam 5Mp, haut-parleurs. Avec WiFi 6 et Bluetooth 5.0, il se connecte à tout sans fil. Idéal pour le télétravail, les études, et l'usage familial.",
  },
  {
    id: 'lenovo-ideacentre-aio-3',
    brand: 'Lenovo', subcategory: 'toutunun',
    name: 'IdeaCentre AIO 3 27"', subtitle: 'AMD Ryzen 5 5500U · 8 Go · 512 Go · 27" FHD',
    price: 849, priceKmf: 416900, priceOld: null,
    badge: null, badgeClass: '',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 44,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Lenovo+AIO+27',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=AIO+27+face'],
    features: ['Grand écran 27"', 'Ryzen 5 puissant', 'Webcam pop-up', 'Clavier + souris inclus'],
    specs: {
      'Processeur': 'AMD Ryzen 5 5500U (6 cœurs, jusqu\'à 4.0 GHz)',
      'Mémoire RAM': '8 Go DDR4 3200 MHz',
      'Stockage': '512 Go SSD PCIe NVMe',
      'Écran': '27" Full HD IPS (1920×1080), anti-reflets, 75Hz',
      'Webcam': 'FHD avec mécanisme pop-up (anti-espionnage)',
      'Audio': 'Haut-parleurs stéréo 5W',
      'Connectique': '1× USB-C, 3× USB 3.2, 2× USB 2.0, HDMI in/out, lecteur SD',
      'Réseau': 'WiFi 5, Bluetooth 5.1, RJ45',
      'Fourni avec': 'Clavier filaire + souris optique',
      'Garantie': '24 mois constructeur',
    },
    description: "Le Lenovo IdeaCentre AIO 3 27\" offre une surface de travail généreuse qui change la vie. Son écran 27\" Full HD IPS est parfait pour les feuilles de calcul, le montage photo léger, ou regarder des films. La webcam pop-up est une fonctionnalité unique : elle disparaît dans l'écran quand vous ne l'utilisez pas. Livré avec clavier et souris.",
  },
  {
    id: 'acer-aspire-c24',
    brand: 'Acer', subcategory: 'toutunun',
    name: 'Aspire C24-1800', subtitle: 'Intel Core i5-1335U · 16 Go · 512 Go · 23.8" FHD',
    price: 649, priceKmf: 318600, priceOld: 749,
    badge: 'Promo', badgeClass: 'badge--promo',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 53,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Acer+Aspire+C24',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=C24+face'],
    features: ['16 Go RAM', 'i5-1335U 12e gen', 'Design ultra-fin', '-100€ promo'],
    specs: {
      'Processeur': 'Intel Core i5-1335U (10 cœurs, jusqu\'à 4.6 GHz)',
      'Mémoire RAM': '16 Go DDR5 4800 MHz',
      'Stockage': '512 Go SSD NVMe',
      'Écran': '23.8" Full HD IPS (1920×1080), 100Hz, anti-reflets',
      'Système': 'Windows 11 Home',
      'Connectique': '1× USB-C 3.2, 2× USB 3.2, 2× USB 2.0, HDMI, lecteur SD, jack',
      'Réseau': 'WiFi 6E, Bluetooth 5.3, RJ45',
      'Fourni avec': 'Clavier + souris sans fil',
      'Garantie': '24 mois constructeur',
    },
    description: "L'Acer Aspire C24-1800 est en promotion exceptionnelle à 649€ au lieu de 749€. Avec 16 Go de RAM DDR5 et le Core i5-1335U de 12e génération, c'est l'un des tout-en-un les plus performants de sa catégorie. Son WiFi 6E garantit des connexions ultra-rapides si vous avez un routeur compatible.",
  },
  {
    id: 'dell-inspiron-24-aio',
    brand: 'Dell', subcategory: 'toutunun',
    name: 'Inspiron 24 AIO 5420', subtitle: 'Intel Core i5-1335U · 8 Go · 512 Go · 23.8" FHD Touch',
    price: 799, priceKmf: 392300, priceOld: null,
    badge: 'Nouveau', badgeClass: 'badge--new',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 31,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Dell+Inspiron+24+AIO',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=Inspiron+AIO+face'],
    features: ['Écran tactile FHD', 'Support réglable en hauteur', 'Webcam 5Mp IA', 'Haut-parleurs Waves Audio'],
    specs: {
      'Processeur': 'Intel Core i5-1335U (10 cœurs, jusqu\'à 4.6 GHz)',
      'Mémoire RAM': '8 Go DDR5 4800 MHz',
      'Stockage': '512 Go SSD PCIe Gen4 NVMe',
      'Écran': '23.8" Full HD IPS Tactile (1920×1080), anti-reflets',
      'Système': 'Windows 11 Home',
      'Webcam': '5 Mp FHD — réduction de bruit IA',
      'Audio': 'Haut-parleurs Waves Audio MaxxBass',
      'Connectique': '1× USB-C 3.2, 2× USB 3.2, 2× USB 2.0, HDMI, lecteur SD, jack',
      'Réseau': 'WiFi 6, Bluetooth 5.2, RJ45',
      'Garantie': '24 mois constructeur',
    },
    description: "Le Dell Inspiron 24 AIO 5420 est le tout-en-un le plus complet de notre gamme. Son écran tactile de 23.8\" ouvre de nouvelles façons de travailler et de créer. La webcam 5 Mp avec réduction de bruit par IA garantit des appels vidéo de qualité professionnelle. Son support réglable en hauteur permet d'adapter l'écran à sa posture idéale.",
  },
  {
    id: 'hp-envy-27',
    brand: 'HP', subcategory: 'toutunun',
    name: 'Envy 27-cs0018nf', subtitle: 'Intel Core i7-1255U · 16 Go · 1 To SSD · 27" 4K',
    price: 1099, priceKmf: 539600, priceOld: null,
    badge: 'Premium', badgeClass: 'badge--new',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 22,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=HP+Envy+27+4K',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=Envy+27+face'],
    features: ['Écran 4K UHD 27"', 'Core i7 + Iris Xe', '1 To SSD', 'Audio Bang & Olufsen'],
    specs: {
      'Processeur': 'Intel Core i7-1255U (10 cœurs, jusqu\'à 4.7 GHz)',
      'Mémoire RAM': '16 Go DDR4 3200 MHz',
      'Stockage': '1 To SSD PCIe NVMe',
      'Écran': '27" 4K UHD (3840×2160) IPS, anti-reflets, Touch optionnel',
      'Système': 'Windows 11 Home',
      'Webcam': '5 Mp FHD 88° ultra-large',
      'Audio': 'Haut-parleurs Bang & Olufsen 6W × 2',
      'Connectique': '2× USB-C Thunderbolt 4, 3× USB 3.2, HDMI 2.0, lecteur SD UHS-II',
      'Réseau': 'WiFi 6E, Bluetooth 5.3',
      'Garantie': '24 mois constructeur',
    },
    description: "Le HP Envy 27 est le tout-en-un haut de gamme de notre catalogue. Son écran 4K UHD de 27\" est absolument magnifique pour la photo, la vidéo, et le design. Les haut-parleurs Bang & Olufsen délivrent un son riche et précis. Avec 16 Go de RAM et 1 To de SSD, il est configuré pour durer 5 à 7 ans sans aucun compromis.",
  },

  /* ── RECONDITIONNÉS ──────────────────────────────── */
  {
    id: 'lenovo-thinkpad-t470',
    brand: 'Lenovo', subcategory: 'reconditiones',
    name: 'ThinkPad T470', subtitle: 'Intel Core i5-7200U · 8 Go · 256 Go SSD · 14" FHD',
    price: 219, priceKmf: 107500, priceOld: 489,
    badge: 'Grade A', badgeClass: 'badge--reco',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 89,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=ThinkPad+T470',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=T470+face','https://placehold.co/500x380/f1f5f9/64748b?text=T470+ports'],
    features: ['Clavier ThinkPad légendaire', 'Rétroéclairé', 'USB-C + HDMI', 'Garanti 6 mois'],
    specs: {
      'Processeur': 'Intel Core i5-7200U (2 cœurs 4 threads, jusqu\'à 3.1 GHz)',
      'Mémoire RAM': '8 Go DDR4 2133 MHz',
      'Stockage': '256 Go SSD SATA (remplacé neuf)',
      'Écran': '14" Full HD IPS (1920×1080), anti-reflets',
      'Connectique': '1× USB-C 3.1, 2× USB 3.0, 1× USB 2.0, HDMI, VGA, jack, lecteur SD',
      'Réseau': 'WiFi 5, Bluetooth 4.2, RJ45',
      'Clavier': 'Rétroéclairé, résistant aux éclaboussures',
      'Autonomie': '~8h (batterie remplacée si < 80%)',
      'Poids': '1.68 kg',
      'État': 'Grade A — cosmétique quasi-parfait, aucune marque visible',
      'Garantie': '6 mois Alkamar Info',
    },
    description: "Le ThinkPad T470 reconditionné Grade A est l'un des meilleurs rapports qualité/prix du marché. Sa construction en magnesium-aluminium, son clavier rétroéclairé et son port USB-C en font un outil professionnel fiable. Chaque machine a été nettoyée, testée (batterie, clavier, écran, ports), et certifiée Grade A par nos techniciens avant expédition.",
  },
  {
    id: 'hp-elitebook-840-g3',
    brand: 'HP', subcategory: 'reconditiones',
    name: 'EliteBook 840 G3', subtitle: 'Intel Core i5-6300U · 8 Go · 256 Go SSD · 14" FHD',
    price: 199, priceKmf: 97700, priceOld: 419,
    badge: 'Grade A', badgeClass: 'badge--reco',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 67,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=EliteBook+840+G3',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=840+G3+face'],
    features: ['Coque aluminium brossé', 'Lecteur empreinte', 'USB-C', 'Garanti 6 mois'],
    specs: {
      'Processeur': 'Intel Core i5-6300U (2 cœurs 4 threads, jusqu\'à 3.0 GHz)',
      'Mémoire RAM': '8 Go DDR4',
      'Stockage': '256 Go SSD (neuf)',
      'Écran': '14" Full HD (1920×1080) IPS, anti-reflets',
      'Connectique': '1× USB-C, 2× USB 3.0, HDMI, VGA, jack, lecteur SD, RJ45',
      'Sécurité': 'Lecteur d\'empreinte digitale',
      'Réseau': 'WiFi 5, Bluetooth, RJ45 Gigabit',
      'État': 'Grade A — traces légères non visibles à l\'usage',
      'Garantie': '6 mois Alkamar Info',
    },
    description: "L'HP EliteBook 840 G3 est un ultrabook professionnel reconditionné au rapport qualité/prix imbattable. Sa coque en aluminium brossé lui donne un look premium et une robustesse excellente. Le lecteur d'empreinte digitale permet une connexion sécurisée et rapide. À 199€ seulement, c'est l'entrée idéale dans l'écosystème professionnel HP.",
  },
  {
    id: 'dell-latitude-5490',
    brand: 'Dell', subcategory: 'reconditiones',
    name: 'Latitude 5490', subtitle: 'Intel Core i5-8250U · 16 Go · 512 Go SSD · 14" FHD',
    price: 289, priceKmf: 141900, priceOld: 629,
    badge: 'Grade A', badgeClass: 'badge--reco',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 112,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Dell+Latitude+5490',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=5490+face'],
    features: ['16 Go RAM', '512 Go SSD', 'Compatible dock Dell', 'Garanti 6 mois'],
    specs: {
      'Processeur': 'Intel Core i5-8250U (4 cœurs 8 threads, jusqu\'à 3.4 GHz)',
      'Mémoire RAM': '16 Go DDR4 2400 MHz',
      'Stockage': '512 Go SSD NVMe',
      'Écran': '14" Full HD IPS (1920×1080)',
      'Connectique': '2× USB-C (dont 1 Thunderbolt 3), 3× USB 3.0, HDMI, jack, lecteur SD, RJ45',
      'Sécurité': 'Lecteur d\'empreinte, TPM 2.0',
      'Réseau': 'WiFi 5, Bluetooth 4.2, RJ45 Gigabit',
      'Compatibilité': 'Dell Dock WD19, WD22',
      'État': 'Grade A — aucune marque visible',
      'Garantie': '6 mois Alkamar Info',
    },
    description: "Le Dell Latitude 5490 reconditionné Grade A est notre best-seller dans la catégorie reconditionnés. Avec 16 Go de RAM et 512 Go de SSD, il offre des performances que de nombreux portables neufs à 600€ ne peuvent pas égaler. Sa compatibilité avec les docks Dell le rend idéal pour les bureaux avec multi-écrans.",
  },
  {
    id: 'lenovo-thinkpad-t480s',
    brand: 'Lenovo', subcategory: 'reconditiones',
    name: 'ThinkPad T480s', subtitle: 'Intel Core i5-8250U · 8 Go · 256 Go SSD · 14" FHD',
    price: 320, priceKmf: 157100, priceOld: 699,
    badge: 'Grade A', badgeClass: 'badge--reco',
    stock: 'Stock limité', stockClass: 'low-stock',
    rating: 5, ratingCount: 145,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=ThinkPad+T480s',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=T480s+face'],
    features: ['Ultra léger 1.65 kg', 'Autonomie 12h', 'USB-C charge', 'Garanti 6 mois'],
    specs: {
      'Processeur': 'Intel Core i5-8250U (4 cœurs 8 threads, jusqu\'à 3.4 GHz)',
      'Mémoire RAM': '8 Go DDR4 2400 MHz',
      'Stockage': '256 Go SSD NVMe',
      'Écran': '14" Full HD IPS (1920×1080), anti-reflets',
      'Connectique': '2× USB-C (Thunderbolt 3), 2× USB 3.0, HDMI, jack',
      'Batterie': 'Dual battery — autonomie ~12h',
      'Réseau': 'WiFi 5, Bluetooth, RJ45',
      'Poids': '1.65 kg',
      'État': 'Grade A',
      'Garantie': '6 mois Alkamar Info',
    },
    description: "Le ThinkPad T480s est l'ultraportable professionnel par excellence. À seulement 1.65 kg, il est parmi les plus légers de sa catégorie tout en intégrant deux batteries pour une autonomie record de 12h. La charge USB-C permet d'utiliser n'importe quelle batterie externe moderne. Un investissement durable.",
  },
  {
    id: 'hp-elitebook-850-g5',
    brand: 'HP', subcategory: 'reconditiones',
    name: 'EliteBook 850 G5', subtitle: 'Intel Core i7-8550U · 16 Go · 512 Go SSD · 15.6" FHD',
    price: 369, priceKmf: 181200, priceOld: 879,
    badge: 'Grade A', badgeClass: 'badge--reco',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 78,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=EliteBook+850+G5',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=850+G5+face'],
    features: ['Core i7 8e gen', '16 Go RAM', 'Grand 15.6"', 'Garanti 6 mois'],
    specs: {
      'Processeur': 'Intel Core i7-8550U (4 cœurs 8 threads, jusqu\'à 4.0 GHz)',
      'Mémoire RAM': '16 Go DDR4',
      'Stockage': '512 Go SSD NVMe',
      'Écran': '15.6" Full HD IPS (1920×1080)',
      'Connectique': '2× USB-C, 2× USB 3.0, HDMI, VGA, jack, lecteur SD, RJ45',
      'Sécurité': 'Lecteur empreinte, lecteur carte à puce',
      'Réseau': 'WiFi 5, Bluetooth, RJ45',
      'État': 'Grade A',
      'Garantie': '6 mois Alkamar Info',
    },
    description: "L'HP EliteBook 850 G5 est le grand-format de notre gamme reconditionnée. Son Core i7-8550U avec 16 Go de RAM permet de faire tourner des applications professionnelles lourdes : ERP, comptabilité, développement. Le lecteur de carte à puce intégré répond aux exigences des administrations et entreprises réglementées.",
  },

  /* ── MINI PC ─────────────────────────────────────── */
  {
    id: 'beelink-mini-s12-pro',
    brand: 'Beelink', subcategory: 'minipc',
    name: 'Mini S12 Pro', subtitle: 'Intel N100 · 8 Go · 256 Go SSD · WiFi 6 · BT 5.2',
    price: 189, priceKmf: 92800, priceOld: null,
    badge: 'Meilleure vente', badgeClass: 'badge--deal',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 421,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Beelink+Mini+S12+Pro',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=Mini+S12+face','https://placehold.co/500x380/f1f5f9/64748b?text=Mini+S12+ports'],
    features: ['Intel N100 efficace', '2x HDMI 4K', 'Silencieux sans ventilateur', 'Windows 11 Pro'],
    specs: {
      'Processeur': 'Intel Alder Lake N100 (4 cœurs, jusqu\'à 3.4 GHz)',
      'Mémoire RAM': '8 Go DDR4 3200 MHz',
      'Stockage': '256 Go SSD M.2 (extensible)',
      'Affichage': '2× HDMI 2.0 (4K@60Hz) — dual monitor',
      'Système': 'Windows 11 Pro',
      'Connectique': '4× USB 3.2, 1× USB 2.0, 2× HDMI, RJ45 2.5G, jack',
      'Réseau': 'WiFi 6 (802.11ax), Bluetooth 5.2',
      'Format': 'Ultra-compact (118 × 113 × 37 mm)',
      'Poids': '420 g',
      'Consommation': '10-15W max — très économe',
      'Garantie': '24 mois',
    },
    description: "Le Beelink Mini S12 Pro est notre best-seller Mini PC — et pour cause. L'Intel N100 consomme seulement 6W TDP tout en offrant des performances bureautiques excellentes. Ses 2 ports HDMI 4K permettent de connecter deux écrans. Totalement silencieux grâce à son refroidissement passif optimisé, c'est le PC parfait pour un bureau calme ou un salon.",
  },
  {
    id: 'gmktec-nucbox-g3',
    brand: 'GMKtec', subcategory: 'minipc',
    name: 'NucBox G3', subtitle: 'Intel N97 · 8 Go · 512 Go SSD · WiFi 6 · Windows 11',
    price: 219, priceKmf: 107500, priceOld: null,
    badge: 'Nouveau', badgeClass: 'badge--new',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 134,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=GMKtec+NucBox+G3',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=NucBox+face'],
    features: ['512 Go SSD', 'Intel N97 plus puissant', 'Volume 0.4L', 'USB-C inclus'],
    specs: {
      'Processeur': 'Intel Alder Lake N97 (4 cœurs, jusqu\'à 3.6 GHz)',
      'Mémoire RAM': '8 Go DDR4 3200 MHz',
      'Stockage': '512 Go SSD M.2 SATA',
      'Affichage': '2× HDMI 4K, 1× USB-C DP — triple monitor',
      'Système': 'Windows 11 Pro',
      'Connectique': '4× USB 3.2, 1× USB-C 3.1, 2× HDMI, RJ45 Gigabit, jack',
      'Réseau': 'WiFi 6, Bluetooth 5.2',
      'Format': 'Ultra-compact 0.4L',
      'Consommation': '12-18W max',
      'Garantie': '24 mois',
    },
    description: "Le GMKtec NucBox G3 monte en puissance par rapport au Mini S12 avec l'Intel N97 et surtout 512 Go de SSD. Sa particularité : il supporte jusqu'à 3 écrans simultanément (2× HDMI + 1× USB-C DisplayPort), idéal pour les postes de trading, de monitoring ou les configurations multi-moniteurs. Malgré sa taille de 0.4L seulement, il est étonnamment capable.",
  },
  {
    id: 'asus-nuc-14-pro',
    brand: 'Asus', subcategory: 'minipc',
    name: 'NUC 14 Pro+', subtitle: 'Intel Core Ultra 5 125H · Sans RAM/SSD configurable',
    price: 499, priceKmf: 245000, priceOld: null,
    badge: null, badgeClass: '',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 56,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Asus+NUC+14+Pro',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=NUC+14+face'],
    features: ['Core Ultra 5 — IA intégrée', 'Thunderbolt 4', 'WiFi 6E', 'RAM/SSD au choix'],
    specs: {
      'Processeur': 'Intel Core Ultra 5 125H (14 cœurs, jusqu\'à 4.5 GHz, NPU IA)',
      'RAM': 'Non inclus — 2× slot DDR5 SO-DIMM (max 96 Go)',
      'Stockage': 'Non inclus — 2× M.2 2280 NVMe',
      'Affichage': '2× Thunderbolt 4 (DP2.1), 2× HDMI 2.1 — quad monitor 4K',
      'Connectique': '2× Thunderbolt 4, 4× USB 3.2, 2× HDMI 2.1, RJ45 2.5G, jack, lecteur SD',
      'Réseau': 'WiFi 6E (802.11axe), Bluetooth 5.3',
      'Format': 'Mini (117 × 112 × 54 mm)',
      'Consommation': 'Configurable 15-65W',
      'Garantie': '24 mois constructeur',
    },
    description: "L'Asus NUC 14 Pro+ est le Mini PC ultime pour les professionnels. Son Intel Core Ultra 5 125H embarque un NPU (Neural Processing Unit) pour les fonctions d'IA Windows 11 Copilot. Il supporte jusqu'à 4 écrans 4K simultanément via ses 2 ports Thunderbolt 4 et 2 HDMI 2.1. Vendu sans RAM ni SSD pour que vous choisissiez exactement la configuration dont vous avez besoin.",
  },
  {
    id: 'minisforum-um773',
    brand: 'Minisforum', subcategory: 'minipc',
    name: 'UM773 Lite', subtitle: 'AMD Ryzen 7 7735HS · 16 Go · 512 Go SSD · WiFi 6',
    price: 329, priceKmf: 161500, priceOld: null,
    badge: 'Nouveau', badgeClass: 'badge--new',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 5, ratingCount: 89,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Minisforum+UM773',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=UM773+face'],
    features: ['Ryzen 7 — puissance laptop', '16 Go DDR5', '512 Go PCIe Gen4', 'Radeon 680M intégré'],
    specs: {
      'Processeur': 'AMD Ryzen 7 7735HS (8 cœurs 16 threads, jusqu\'à 4.75 GHz)',
      'GPU intégré': 'AMD Radeon 680M (12 CUs) — gaming léger possible',
      'Mémoire RAM': '16 Go DDR5 4800 MHz',
      'Stockage': '512 Go SSD PCIe Gen4 NVMe',
      'Affichage': '1× HDMI 2.1, 1× DP 1.4, 1× USB-C DP — triple 4K',
      'Connectique': '2× USB4 (40 Gbps), 2× USB 3.2, 2× USB 2.0, HDMI, DP, RJ45 2.5G',
      'Réseau': 'WiFi 6E, Bluetooth 5.3',
      'Format': '127 × 127 × 48 mm',
      'Garantie': '24 mois',
    },
    description: "Le Minisforum UM773 Lite est une bête de puissance dans un format mini. Son Ryzen 7 7735HS (processeur de PC portable haute performance) offre des performances qui rivalisent avec des tours bureau à 700€. La puce graphique Radeon 680M intégrée permet même de jouer à des titres moins gourmands (FIFA, League of Legends, Valorant) en 1080p medium.",
  },
  {
    id: 'beelink-eq12',
    brand: 'Beelink', subcategory: 'minipc',
    name: 'EQ12', subtitle: 'Intel N100 · 16 Go · 500 Go SSD · WiFi 6 · BT 5.2',
    price: 239, priceKmf: 117300, priceOld: null,
    badge: 'Bon prix', badgeClass: 'badge--deal',
    stock: 'En stock', stockClass: 'in-stock',
    rating: 4, ratingCount: 203,
    image: 'https://placehold.co/500x380/f1f5f9/64748b?text=Beelink+EQ12',
    gallery: ['https://placehold.co/500x380/f1f5f9/64748b?text=EQ12+face'],
    features: ['16 Go RAM', '500 Go SSD', 'Dual HDMI 4K', 'Ventilateur silencieux'],
    specs: {
      'Processeur': 'Intel N100 (4 cœurs, jusqu\'à 3.4 GHz)',
      'Mémoire RAM': '16 Go DDR5 4800 MHz',
      'Stockage': '500 Go SSD M.2 PCIe',
      'Affichage': '2× HDMI 2.0 (4K@60Hz)',
      'Connectique': '4× USB 3.2, 1× USB-C, 2× HDMI, RJ45 2.5G, jack',
      'Réseau': 'WiFi 6, Bluetooth 5.2',
      'Format': 'Compact (116 × 108 × 38 mm)',
      'Consommation': '~12W',
      'Garantie': '24 mois',
    },
    description: "Le Beelink EQ12 est la version premium du Mini S12 Pro, avec 16 Go de RAM DDR5 et 500 Go de SSD. Idéal pour les utilisateurs qui font tourner plusieurs applications simultanément : navigateur avec 20 onglets, Zoom, suite Office, et logiciel métier en même temps. Un excellent choix pour doper un poste de travail existant à petit prix.",
  },
];

// Accès rapide par ID
const PRODUCTS_BY_ID = Object.fromEntries(PRODUCTS.map(p => [p.id, p]));
